title: Yang Liu's Homepage
page-top-title: Yang Liu
top-section-bg-text: Biomedical Engineering
home-subtitle: Yang Liu&ensp;|&ensp;刘洋
copyright-text: '&copy; Yang Liu 2022-2026. All Rights Reserved.'
